version: '3.8'

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=super_secret_key  # Definindo a SECRET_KEY para gerar tokens JWT
    volumes:
      - ./auth_service:/app  # Montando o código local para o contêiner

  book_service:
    build: ./book_service
    container_name: book_service
    ports:
      - "8002:8002"
    depends_on:
      - auth_service
    environment:
      - SECRET_KEY=super_secret_key  # Mesma SECRET_KEY para validar tokens JWT
    volumes:
      - ./book_service:/app  # Montando o código local para o contêiner

  notification_service:
    build: ./notification_service
    container_name: notification_service
    ports:
      - "8003:8003"
    depends_on:
      - book_service
    volumes:
      - ./notification_service:/app  # Montando o código local para o contêiner

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - auth_service
      - book_service
      - notification_service
    volumes:
      - ./client:/app  # Montando o código local para o contêiner
